### ISSUE TITLE
Create skeleton code for Android app

### ISSUE THREAD

**Issue by bpowell** [bpowell/cse480#10]

**Comment by jelevoir** [comment]
Not enough time. More important things to work on and the site works good enough on mobile browsers.
We can use (I'm sorry for suggesting them because I think they're awful) QR codes to launch the site on mobile. I think the judges would like that rather than suggesting we tell drunk people to open their phones and type in drinkq.me.

**Comment by bpowell** [comment]
Works for me, closing issue.
