### ISSUE TITLE
Same service??

### ISSUE THREAD

**Issue by bpowell** [bpowell/cse480#201]
@jelevoir take a look at BarDrinkOrder (service and model) and compare it to DrinkOrder (service and model). It looks like they are doing the same thing, with BarDrinkOrder actually being used and is more correct. Can we delete DrinkOrderSerivce and DrinkOrder? This would also fix #197 by removing the offending code.

**Comment by jelevoir** [comment]
Yeah. I think I created that near the beginning of the project and I was using it for something specific (and I was far less knowledgeable about MVC).

It has since grown to be what I have been using for getting and setting information about a bars drink orders.

So, as long as nothing breaks, we should be able to remove DrinkOrderService and DrinkOrder.

**Comment by bpowell** [comment]
Okay cool beans, I will do that.
