### ISSUE TITLE
Add navigation functionality to header

### ISSUE THREAD

**Issue by ghost** [bpowell/cse480#79]

**Comment by jelevoir** [comment]
@dcfreema 
So the easiest way (IMO) as well as correct, would be:
- Change the tag for each link from 'button' to 'a'.
- Remove the 'value' attribute.
- Remove the 'type' attribute.
- Add an 'href' attribute with value specific to page. 

An example would look like

> `<a href="<c:url value="/barview" />" class="btn btn-lg btn-primary btn-block">View Bars</a>`

Doing so, you will keep whatever styling you have done for the buttons.

**Comment by jelevoir** [comment]
Also, you may want to look into using [collapsible navbars](http://v4-alpha.getbootstrap.com/components/navbar/#collapsible-content). This will give us a menu that appears on press of the menu icon (hamburger icon) when a visitor is viewing the page on a mobile device.

Also, I noticed when looking at the header file that we are missing bootstrap's JS component.
On a related note, I think we should be using bootstrap's CDN instead of having users rely on our local copy. It will make loading faster as users are likely to have it cached from visiting other websites.

**Comment by jelevoir** [comment]
Here are the Bootstrap v4's CDN links (keep in mind you'll have to remove the integrity and crossorigin attributes, unless you want to generate it's sha384 and plug it in where the XX's are):

> `<link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css" integrity="sha384-XXXXXXXX" crossorigin="anonymous">`
> `<script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js" integrity="sha384-XXXXXXXX" crossorigin="anonymous"></script>`
